# JPA configuration
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:devdb
    username: sa
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  #H2 database
  h2:
    console:
      path: /h2-console
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:18080/realms/loja-virtual-realm/protocol/openid-connect/certs
          issuer-uri: http://localhost:18080/auth/realms/loja-virtual-realm


management:
  health:
    db:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  info:
    build:
      enabled: true
    env:
      enabled: true
    git:
      enabled: true
    java:
      enabled: true
